DROP TABLE CrewList;
DROP TABLE CastList;
DROP TABLE RatingList;
DROP TABLE Movies;

CREATE TABLE Movies (
	movie_id integer NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_MOVIEFACTTABLE PRIMARY KEY,
    title varchar(500) NULL,
	year varchar(4) NULL,
	isAdult integer NULL,
	runtime varchar (10) NULL,
	genre1 varchar(50) NULL,
	genre2 varchar(50) NULL,
	genre3 varchar(50) NULL,

	CrewFK integer UNIQUE NULL,
    crewNumber integer NULL,

	CastFK integer UNIQUE NULL,
    castNumber integer NULL,

    RatingsFK integer UNIQUE NULL,
    avgRating double precision NULL,
	numOfVotes integer NULL
	
);


CREATE TABLE CrewList (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_CREWLIST PRIMARY KEY,
	type varchar(100) NULL,
	name varchar(100) NULL,
	CrewListFK integer NULL

);

CREATE TABLE CastList (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_CASTLIST PRIMARY KEY,
	name varchar(100) NULL,
	character varchar(250) NULL,
	CastListFK integer NULL,
	birth varchar(4) NULL,
	death varchar(4)

);

CREATE TABLE RatingList (
	id integer GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_RATINGLIST PRIMARY KEY,
	userID integer NULL,
	rating decimal(18,0) NULL,
	RatingListFK integer NULL
);


SELECT 1 movie_id;
