ALTER TABLE CrewList ADD CONSTRAINT CrewList_fk0 FOREIGN KEY (CrewListFK) REFERENCES Movies(movie_id)
ON UPDATE CASCADE;
 
ALTER TABLE CrewList VALIDATE CONSTRAINT CrewList_fk0;
 
ALTER TABLE CastList ADD CONSTRAINT CastList_fk0 FOREIGN KEY (CastListFK) REFERENCES Movies(movie_id)
ON UPDATE CASCADE;
 
ALTER TABLE CastList VALIDATE CONSTRAINT CastList_fk0;

ALTER TABLE RatingList ADD CONSTRAINT RatingList_fk0 FOREIGN KEY (RatingListFK) REFERENCES Movies(movie_id)
ON UPDATE CASCADE;
 
ALTER TABLE RatingList VALIDATE CONSTRAINT RatingList_fk0;

SELECT 1 tmp 
